### PR TITLE
Use varbits + fix overlays

### PR DESCRIPTION
**Pull request by Fjara-h**
I made it use varbits instead of dialogue. I cleaned up some various stuff and organized a bit. Pulled out the enum to its own file. The tooltip + item overlay weren't working on the current build for me, so I fixed that. It also never has to access user config for info because it pulls varbits on login.

### CODE REVIEW

**Comment by geheur** [comment]
Nice, that is way easier than reading the dialog.
3 questions:
How much did you test this?
What is the purpose of using the hasEasy, etc. static variables, rather than reading the varbits directly?
Why did you make some methods static such as watsonHasClue, when all the places that use those methods have access to an instance of the plugin class?

**Comment by Fjara-h** [comment]
1. I started with an easy handed in already. Dropped a med/hard clue, switched worlds, handing both in, and got new ones. I've checked when they are in bank, equipment stat, normal inventory, and inventory when bank is open. Also had other items in my inventory to verify the tooltip/overlay would not appear on them. I've not yet claimed a master because elites are taking me a while to get so I'm still working on it. I also made sure to check it while next to him and very far away in case they were only readable in a local area. If there are other things you'd like verified I can do that as well. I plan on getting an elite and having a med/easy in my inventory when I claim.
2. I used hasEasy as a way to mimic the formatting previously used and it was an easy way to reference the value rather than calling getvarbitvalue repeatedly. I'm open to changing it if desired.
3. Intellij's errors of: "Non-static method 'watsonHasClue(com.watsoncluetracker.ClueTier)' cannot be referenced from a static context" referenceing line 52 on WatsonWidgetOverlayItem.java. That could be resolved by using getvarbitvalue directly

**Comment by Fjara-h** [comment]
[output.webm](https://user-images.githubusercontent.com/22579764/229230227-516e184a-7e54-4b16-beaf-d07eb1f925d8.webm)
Finally got an elite clue. Works. Should I make it so that the "W" on the item overlay is colored to that clue or leave it the static blue (as it was previously)

**Comment by geheur** [comment]
good to see it working! I handed in an easy earlier today and it also seemed to work.
idc about the "w" color. It's a very confusing bit of UI tbh, I always forget what it means myself lol.

Anyways, I have some small edits to make here, do you care if I squash a bunch of stuff together with some edits and force-push the PR branch? I don't have much experience with PRs so idk what the best practice is.

**Comment by Fjara-h** [comment]
Go for it

**Pull request merged**
